create table if not exists public.user_module_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module text not null,
  scope_key text not null default 'default',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module, scope_key)
);

create index if not exists user_module_data_user_module_idx
  on public.user_module_data (user_id, module);

create or replace function public.set_user_module_data_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_module_data_updated_at on public.user_module_data;
create trigger set_user_module_data_updated_at
  before update on public.user_module_data
  for each row
  execute function public.set_user_module_data_updated_at();

alter table public.user_module_data enable row level security;

drop policy if exists "Users can read their own module data" on public.user_module_data;
create policy "Users can read their own module data"
  on public.user_module_data
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own module data" on public.user_module_data;
create policy "Users can insert their own module data"
  on public.user_module_data
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own module data" on public.user_module_data;
create policy "Users can update their own module data"
  on public.user_module_data
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own module data" on public.user_module_data;
create policy "Users can delete their own module data"
  on public.user_module_data
  for delete
  to authenticated
  using (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'user_module_data'
  ) then
    alter publication supabase_realtime add table public.user_module_data;
  end if;
end $$;

do $$
begin
  if to_regclass('public.app_state') is not null then
    insert into public.user_module_data (user_id, module, scope_key, data, created_at, updated_at)
    select
      user_id,
      case storage_key
        when 'ojt-roadmap-store' then 'roadmap'
        when 'ojt-equipment-library' then 'equipment'
        when 'ojt-knowledge-base' then 'knowledge_base'
        when 'ojt-daily-journal' then 'daily_journal'
        when 'ojt-document-library' then 'documents'
        when 'ojt-photo-gallery' then 'gallery'
        when 'ojt-standards-library' then 'standards'
        when 'ojt-generated-reports' then 'reports'
        when 'ojt-notification-center' then 'notifications'
        when 'ojt-recent-searches' then 'recent_searches'
        when 'ojt-user-profile' then 'user_profile'
        when 'ojt-settings' then 'settings'
        when 'ojt-theme' then 'theme'
        when 'ojt-local-backups' then 'local_backups'
        else regexp_replace(regexp_replace(storage_key, '^ojt-', ''), '-', '_', 'g')
      end,
      'default',
      state,
      updated_at,
      updated_at
    from public.app_state
    where storage_key <> 'ojt-weekly-planner'
    on conflict (user_id, module, scope_key) do nothing;

    insert into public.user_module_data (user_id, module, scope_key, data, created_at, updated_at)
    select
      user_id,
      'weekly_planner',
      '__meta',
      jsonb_build_object(
        'version', coalesce(state->'version', '0'::jsonb),
        'selectedWeekId', state#>'{state,selectedWeekId}'
      ),
      updated_at,
      updated_at
    from public.app_state
    where storage_key = 'ojt-weekly-planner'
    on conflict (user_id, module, scope_key) do nothing;

    insert into public.user_module_data (user_id, module, scope_key, data, created_at, updated_at)
    select
      app_state.user_id,
      'weekly_planner',
      'week:' ||
        lpad(coalesce(week.value->>'weekNumber', '0'), 2, '0') ||
        ':' ||
        coalesce(week.value->>'id', 'unknown'),
      week.value,
      app_state.updated_at,
      app_state.updated_at
    from public.app_state
    cross join lateral jsonb_array_elements(coalesce(app_state.state#>'{state,weeks}', '[]'::jsonb)) as week(value)
    where app_state.storage_key = 'ojt-weekly-planner'
    on conflict (user_id, module, scope_key) do nothing;
  end if;
end $$;
